### ISSUE TITLE
Issues with reduce

### ISSUE THREAD

**Issue by pranavtbhat** [shashi/ComputeFramework.jl#6]
I'm using the following example for `reduce`

```julia
addprocs(2)
using ComputeFramework

numbers = [1, 2, 3 ,4, 5, 6, 7, 8, 9, 10]
parallel_numbers = distribute(numbers)
sum_of_numbers = reduce(+, 0.0, parallel_numbers)
println(gather(Context(), sum_of_numbers))
```

The first problem is that `reduce` returns a single element array, unlike filter and map. The second problem is that +,- and other arithmetic operators don't have methods that can work with the required types. 
```
MethodError: `+` has no method matching +(::Float64, ::ComputeFramework.Distribute{Array{Int64,1},ComputeFramework.CutDimension{1}})
```
However `push!` works just fine:
```julia
sum_of_numbers = reduce(push!, 0.0, parallel_numbers)
````

**Comment by rohitvarkey** [comment]
Calling `gather` on a `MapReduceNode` will give an error. `compute` will get the value for you in this case without requiring a `gather`.

@shashi Should we create a special `gather` for `MapReduceNode`s, where it doesn't call `gather` on the computed values but just returns `compute`?

**Comment by pranavtbhat** [comment]
Using Compute gives similar results. I don't think that's the problem.

**Comment by rohitvarkey** [comment]
There was an issue which #7 solves. If you use `compute` on that branch, this should work. `gather` will give an error on #7 too.

**Comment by pranavtbhat** [comment]
Ah okay.
