### ISSUE TITLE
mappart infinte loop

### ISSUE THREAD

**Issue by pranavtbhat** [shashi/ComputeFramework.jl#8]
This produces an infinite loop:
```julia
gather(Context(), map( (x,y)->x, distribute(zeros(10)), distribute(zeros(10,10))))
```
The dimensions on the inputs don't match, but I need this to load the adjacency matrix and dist vector onto nodes.

The infinite recursion is in this function in `compute-nodes.jl`:
```julia
function compute(ctx, x::MapPartNode)
   compute(ctx, MapPartNode(x.f, map(inp -> compute(ctx, inp), x.input)))
end
```

Usually the recursion is terminated by this function in `dist-memory.jl`:
```julia
 function compute{N, T<:DistMemory}(ctx, node::MapPartNode{NTuple{N, T}})
    refsets = zip(map(x -> map(y->y[2], refs(x)), node.input)...) |> collect
    pids = map(x->x[1], refs(node.input[1]))
    pid_chunks = zip(pids, map(tuplize, refsets)) |> collect

    let f = node.f
        futures = Pair[pid => @spawnat pid f(map(fetch, rs)...)
                        for (pid, rs) in pid_chunks]
        DistMemory(futures, node.input[1].layout)
    end
end
```

**Comment by shashi** [comment]
I pushed a change to master which should let you do this. i.e. `mappart` will not insist that inputs have the same distribution.

I admit that catch-all method is dumb.

**Comment by shashi** [comment]
(the push had failed, I pushed again)

**Comment by pranavtbhat** [comment]
Its working fine now. Thanks!
